// AUTO-GENERATED — DO NOT EDIT.
//
// .pg → TypeScript typed attrs (wire-normalized), generated by
// @modernrelay/orbit-omnigraph (`orbit-omnigraph-codegen`).
// Schema fingerprint: 7278e0632d9b14ee.
// Source: fixtures/omnigraph/cluster/demo.pg
//
// Shapes describe attrs AFTER the adapter's wire normalization (both read
// paths converge on the query-path string encodings):
//   Date → 'YYYY-MM-DD' · DateTime → ISO 8601 · enum(...) → literal union
//   I64/U64/F32/F64 → number · Vector(n) → number[] · T? → T | null
//   Blob → string ('data:' URI for inline blobs, stored URI for external)

/** Normalized attrs for node type `Actor`. */
export interface ActorProps {
  /** Physical Omnigraph id — injected into every export line's `data`; unique per node type only. */
  id: string;
  slug: string;
  name: string;
  email: string | null;
  /** `Date` — normalized to 'YYYY-MM-DD' (UTC) on load. */
  joined_at: string;
}

/** Normalized attrs for node type `Decision`. */
export interface DecisionProps {
  /** Physical Omnigraph id — injected into every export line's `data`; unique per node type only. */
  id: string;
  slug: string;
  title: string;
  body: string | null;
  status: 'proposed' | 'accepted' | 'rejected' | 'superseded';
  urgency: 'low' | 'normal' | 'high' | 'critical';
  /** `Date` — normalized to 'YYYY-MM-DD' (UTC) on load. */
  decided_at: string | null;
  /** `DateTime` — normalized to ISO 8601 UTC on load. */
  updated_at: string;
}

/** Normalized attrs for node type `Trace`. */
export interface TraceProps {
  /** Physical Omnigraph id — injected into every export line's `data`; unique per node type only. */
  id: string;
  slug: string;
  title: string;
  body: string | null;
  kind: 'note' | 'discussion' | 'experiment' | 'review' | 'meeting' | 'document';
  /** `DateTime` — normalized to ISO 8601 UTC on load. */
  recorded_at: string;
  /** `I64` — JSON numbers round silently past ±2^53. */
  word_count: number;
  source: string | null;
}

/** Normalized attrs for node type `Signal`. */
export interface SignalProps {
  /** Physical Omnigraph id — injected into every export line's `data`; unique per node type only. */
  id: string;
  slug: string;
  title: string;
  body: string | null;
  category: 'competitor' | 'market' | 'regulatory' | 'technology' | 'customer';
  strength: number;
  /** `Date` — normalized to 'YYYY-MM-DD' (UTC) on load. */
  observed_at: string;
  source: string | null;
}

/** Normalized attrs for node type `Artifact`. */
export interface ArtifactProps {
  /** Physical Omnigraph id — injected into every export line's `data`; unique per node type only. */
  id: string;
  slug: string;
  title: string;
  kind: 'doc' | 'presentation' | 'proposal' | 'spec' | 'report' | 'memo';
  url: string | null;
  /** `Date` — normalized to 'YYYY-MM-DD' (UTC) on load. */
  created_at: string;
  /** `I64` — JSON numbers round silently past ±2^53. */
  revision: number;
}

/** Normalized attrs for edge type `OwnedBy`. */
export interface OwnedByEdgeProps {
  /** Physical Omnigraph id — injected into every export line's `data`; unique per edge type only. */
  id: string;
}

/** Normalized attrs for edge type `ParticipatedIn`. */
export interface ParticipatedInEdgeProps {
  /** Physical Omnigraph id — injected into every export line's `data`; unique per edge type only. */
  id: string;
}

/** Normalized attrs for edge type `RecordedBy`. */
export interface RecordedByEdgeProps {
  /** Physical Omnigraph id — injected into every export line's `data`; unique per edge type only. */
  id: string;
}

/** Normalized attrs for edge type `Supports`. */
export interface SupportsEdgeProps {
  /** Physical Omnigraph id — injected into every export line's `data`; unique per edge type only. */
  id: string;
  weight: number | null;
}

/** Normalized attrs for edge type `Triggered`. */
export interface TriggeredEdgeProps {
  /** Physical Omnigraph id — injected into every export line's `data`; unique per edge type only. */
  id: string;
}

/** Normalized attrs for edge type `Correlates`. */
export interface CorrelatesEdgeProps {
  /** Physical Omnigraph id — injected into every export line's `data`; unique per edge type only. */
  id: string;
  confidence: number;
}

/** Discriminated union over every node type's normalized attrs — `'orbit:type'` is injected by the adapter. */
export type NodeAttrs =
  | ({ 'orbit:type': 'Actor' } & ActorProps)
  | ({ 'orbit:type': 'Decision' } & DecisionProps)
  | ({ 'orbit:type': 'Trace' } & TraceProps)
  | ({ 'orbit:type': 'Signal' } & SignalProps)
  | ({ 'orbit:type': 'Artifact' } & ArtifactProps);

/** Discriminated union over every edge type's normalized attrs — `'orbit:type'` is the edge name. */
export type EdgeAttrs =
  | ({ 'orbit:type': 'OwnedBy' } & OwnedByEdgeProps)
  | ({ 'orbit:type': 'ParticipatedIn' } & ParticipatedInEdgeProps)
  | ({ 'orbit:type': 'RecordedBy' } & RecordedByEdgeProps)
  | ({ 'orbit:type': 'Supports' } & SupportsEdgeProps)
  | ({ 'orbit:type': 'Triggered' } & TriggeredEdgeProps)
  | ({ 'orbit:type': 'Correlates' } & CorrelatesEdgeProps);

/** Type-name → props lookup for both kinds (closed sets from the schema — the wire contract). */
export interface TypeMap {
  nodes: {
    Actor: ActorProps;
    Decision: DecisionProps;
    Trace: TraceProps;
    Signal: SignalProps;
    Artifact: ArtifactProps;
  };
  edges: {
    OwnedBy: OwnedByEdgeProps;
    ParticipatedIn: ParticipatedInEdgeProps;
    RecordedBy: RecordedByEdgeProps;
    Supports: SupportsEdgeProps;
    Triggered: TriggeredEdgeProps;
    Correlates: CorrelatesEdgeProps;
  };
}

export type NodeTypeName = keyof TypeMap['nodes'];
export type EdgeTypeName = keyof TypeMap['edges'];
